### ISSUE TITLE
The training code of SCN model

### ISSUE THREAD

**Issue by chenboheng** [huangzehao/SCN_Matlab#3]
Hello! I am very interested about this project. But I don't fully understand the training detail of this algorithm. Could you share the caffe training code of SCN recently? Thank you very much.

**Comment by chenboheng** [comment]
Dear @huangzehao 
        I have some problems in the training of SCN model when I have read the test code of SCN_Matlab. In the original LISTA paper (Learning Fast Approximation of sparse coding), W an S must satisfy the relationship: W=(1/L)D^(T) and S=I-(1/L)D^(T)D. But I found that the learned weight model.usd1 and model.wd don't satisfy this relationship. It is means that you train W and S as two completely irrelevant matrix? Dose W and S are two irrelevant or relevant matrix? Does the two irrelevant or relevant matrix will affect the final results?

**Comment by huangzehao** [comment]
Hi! The constraint you said is in ISTA, not LISTA. W and S are learned by back-propagation algorithms. Read LISTA paper carefully and you can get it. 
I have a work about SCN and I submitted it to a conference. But there is not result now. Sorry, I can't share my training code now. 
But actually it's easy to implement the training code. The only difficult is how understand the network structure from original paper. I show it in my code "Demo_SR_Conv.m". Read this code and you can get it.
