### ISSUE TITLE
如何针对我自己的数据，进行.mat的训练，希望作者开源train.m ,test.m, SCN_solver.prototxt.

### ISSUE THREAD

**Issue by xdjwolf** [huangzehao/SCN_Matlab#5]
如何针对我自己的数据，进行.mat的训练，希望作者开源train.m ,test.m, SCN_solver.prototxt.
希望作者可以提供 上述文件，即双字典稀疏编码 时对应的Deep 网络结构，同时渴求作者联系邮箱，小弟有诸多SR的问题想要请教，如作者看到之后及时反馈，小弟将不胜感激。鄙人联系方式 1123098229@qq.com ，跪求大神指导。

**Comment by Hanooooo** [comment]
can the author provide me with the source of the trainning code?I want to learn about it,
looking forward to your reply,Thank you very much!
